### ISSUE TITLE
The Proxy Upgrade Test Suite is often flaky causing re-runs, delays and loss of confidence in the tests.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-smart-contracts#636]
### Description

Some of the failures:
```  1) @OZERC1967Upgrade Upgradable Vote Tests
       Proxy Contract tests
         Should upgrade proxy vote to point to voteV2:

      AssertionError: expected '0xAdCF464072CD9302d3b5bb05f4eD667Cb59…' to equal '0xa2D861570e6aFBC4e0A2538689CB74ee7eA…'
      + expected - actual

      -0xAdCF464072CD9302d3b5bb05f4eD667Cb59b105a
      +0xa2D861570e6aFBC4e0A2538689CB74ee7eAd3A42
```

``` 
15 passing (57s)
  2 failing

  1) Proxy Upgrade Contracts Test Suite
       DEX Upgradable Contract Test Suite
         "before all" hook for "should deposit, buy and sell tokens from ExchangeV1":
     ProviderError: [Request ID: 9f1dbbbb-27ca-4b3a-aec6-94e166f3419d] Transaction gas limit provided '61354' is insufficient of intrinsic gas required '95916'
      at HttpProvider.request (/runner/_work/hedera-smart-contracts/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at EthersProviderWrapper.send (/runner/_work/hedera-smart-contracts/hedera-smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

  2) Proxy Upgrade Contracts Test Suite
       Counter Upgradable Contract Test Suite
         "before all" hook for "should be able to increase and decrease counter on V1":
     ProviderError: [Request ID: 9cdf324f-f495-4668-9dc6-8d6d2787a6db] Transaction gas limit provided '61106' is insufficient of intrinsic gas required '76720'
      at HttpProvider.request (/runner/_work/hedera-smart-contracts/hedera-smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at EthersProviderWrapper.send (/runner/_work/hedera-smart-contracts/hedera-smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)



Error: Process completed with exit code 2.
```

### Steps to reproduce

Run the Proxy Upgrade Tests.  Failures listed above happen in CI.

### Hedera network

other

### Version

v0.7.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
@ebadiere was this resolved or does it still need to be covered?
